[webservers] ;sectionName
server1 host=bandit.labs.overthewire.org user=bandit0 password=bandit0
; server1 host=$HOST_1 user=$USER_HOST_1 password=$PASSWORD_HOST_1
;host_key-> server1 host_value-> host=bandit.labs.overthewire.org user=bandit0
; server2 host=leviathan.labs.overthewire.org user=leviathan0

; [databases] ;sectionName
; db1 host=192.168.1.102 user=rahul