[webservers] ;sectionName
server1 host=host1 user=username password=password
;host_key-> server1 host_value-> host=host1 user=username

; [databases] ;sectionName
; db1 host=192.168.1.102 user=username password=password